// ============================================================================
// SIMULATED DEMO DATA
// All values below are synthetic and for demonstration purposes only.
// They do not represent actual historical rescue assets or real incidents.
// ============================================================================

export type UrgencyLevel = 1 | 2 | 3 | 4 | 5;

export interface Incident {
  vesselId: string;
  vesselName: string;
  vesselType: string;
  position: { lat: number; lon: number };
  speedKts: number;
  headingDeg: number;
  crewAtRisk: number;
  minutesSinceContact: number;
  urgency: UrgencyLevel;
  status: string;
  seaState: string;
  windKts: number;
  currentKts: number;
  waterTempC: number;
  summary?: string;
}

export interface Zone {
  id: string;
  label: string;
  probability: number;
  priority: 1 | 2 | 3 | 4;
  cx: number;
  cy: number;
  rx: number;
  ry: number;
  rationale: string;
}

export interface Asset {
  id: string;
  name: string;
  type: "HELO" | "BOAT";
  speedKts: number;
  enduranceHours: number;
  medicalCapability: boolean;
  etaMin: number;
  rangeNm: number;
  readiness: number;
  status: "READY" | "ENROUTE" | "STANDBY" | "OFFLINE";
  x: number;
  y: number;
  assignedZone?: string;
}

export const INCIDENT: Incident = {
  vesselId: "MV-204",
  vesselName: "MV-204",
  vesselType: "Fishing Vessel",
  position: { lat: 13.04, lon: 80.52 },
  speedKts: 7,
  headingDeg: 140,
  crewAtRisk: 3,
  minutesSinceContact: 20,
  urgency: 4,
  status: "LOSS OF CONTACT",
  seaState: "3 — SLIGHT",
  windKts: 14,
  currentKts: 1.2,
  waterTempC: 28.6,
};

export const ZONES: Zone[] = [
  {
    id: "A",
    label: "ZONE A",
    probability: 0.61,
    priority: 1,
    cx: 46,
    cy: 44,
    rx: 15,
    ry: 11,
    rationale:
      "Leeway drift vector (SE 1.2 kt current + 14 kt wind) places the datum inside Zone A within 20 min of last contact. Highest containment of the probability mass.",
  },
  {
    id: "B",
    label: "ZONE B",
    probability: 0.24,
    priority: 2,
    cx: 63,
    cy: 57,
    rx: 12,
    ry: 9,
    rationale:
      "Down-current expansion cell. Absorbs drift error if the vessel retained partial steerage before contact loss.",
  },
  {
    id: "C",
    label: "ZONE C",
    probability: 0.11,
    priority: 3,
    cx: 33,
    cy: 62,
    rx: 10,
    ry: 8,
    rationale:
      "Counter-eddy scenario near the shelf break. Low weight but non-zero given historical eddy behaviour in this basin.",
  },
  {
    id: "D",
    label: "ZONE D",
    probability: 0.04,
    priority: 4,
    cx: 58,
    cy: 28,
    rx: 9,
    ry: 7,
    rationale:
      "Up-wind residual. Retained only to cover contact timestamp uncertainty of ±3 min.",
  },
];

export const ASSETS: Asset[] = [
  {
    id: "BOAT-01",
    name: "BOAT-01",
    type: "BOAT",
    speedKts: 25,
    enduranceHours: 5,
    medicalCapability: false,
    etaMin: 26,
    rangeNm: 35,
    readiness: 0.92,
    status: "READY",
    x: 24,
    y: 74,
    assignedZone: "A",
  },
  {
    id: "BOAT-02",
    name: "BOAT-02",
    type: "BOAT",
    speedKts: 22,
    enduranceHours: 8,
    medicalCapability: true,
    etaMin: 34,
    rangeNm: 48,
    readiness: 0.88,
    status: "ENROUTE",
    x: 78,
    y: 40,
    assignedZone: "B",
  },
  {
    id: "HELI-01",
    name: "HELI-01",
    type: "HELO",
    speedKts: 120,
    enduranceHours: 2,
    medicalCapability: true,
    etaMin: 12,
    rangeNm: 90,
    readiness: 0.95,
    status: "READY",
    x: 70,
    y: 78,
    assignedZone: "A",
  },
];

export interface CopilotMessage {
  id: string;
  role: "copilot" | "operator";
  text: string;
  ts: string;
}

export const COPILOT_QUESTIONS = [
  {
    q: "Why was this asset selected?",
    a: "The scoring engine evaluated all available asset–zone pairings and ranked them by total cost (response time + hazard penalty + capability penalty + priority bonus). The top-ranked candidate has the lowest cost.",
  },
  {
    q: "Why is this search zone highest priority?",
    a: "Search zones are generated by a Gaussian probability decay model centered on the predicted vessel position. The center cell receives exponentially higher weight. Priority 1 is the zone closest to the predicted fix with the highest probability mass.",
  },
  {
    q: "Why wasn't another asset selected?",
    a: "Alternative assets were evaluated but ranked lower due to longer response times, higher total cost, endurance constraints, or capability penalties in the scoring engine.",
  },
  {
    q: "How did environmental risk affect the decision?",
    a: "The environmental risk engine calculates cyclone proximity and wind intensity factors. Higher risk increases the uncertainty multiplier, which expands search zone radius and adds hazard penalty to each candidate's cost function.",
  },
  {
    q: "What happens if the selected asset fails?",
    a: "The scoring engine maintains a ranked list of all feasible asset–zone pairings. If the primary asset fails, the next-best candidate will be tasked. Response time may increase and coverage confidence may decrease.",
  },
];
